# Lab Work 2: Text Processing: Preparation of texts

Use this notebook for the subsequence excecise's parts

## 6.2.1 Load the data and CountVectorize them
You will find a list of files in Ilias [sherlock.zip](https://www.ili.fh-aachen.de/goto_elearning_file_815003_download.html)
Download the zip file and adapt your next line accordingly.

In [1]:
import pandas as pd
import numpy as np

filenames = [r"C:/Users/alant/Sherlock.txt", 
             r"C:/Users/alant/Sherlock_blanched.txt",
             r"C:/Users/alant/Sherlock_black.txt",
             r"C:/Users/alant/Sherlock_blue.txt",
             r"C:/Users/alant/Sherlock_card.txt"]

Now we create a count Vectorizer. The parameter given tells the CountVectorizer that its methods shall operate on a list of filenames.

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(input="filename")

After using the [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html), I use the `fit_transform` function, which transforms the file names into a document-term matrix.

In [3]:
X = vectorizer.fit_transform(filenames).toarray()
X

array([[0, 1, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]])

### Create a DataFrame for simpler processing of data

In [4]:
df = pd.DataFrame(data=X, columns=vectorizer.get_feature_names_out())
df

,117,12,12s,13,131,13th,14th,15,16,1840,...,yourselves,youth,youthful,youths,yoxley,zealous,zenith,zest,zigzag,zoo
0,0,1,0,1,2,1,1,1,2,1,...,1,5,1,0,7,1,1,1,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,2,0,1,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

The output is a document-term matrix where the order of the words is ignored. Each row of the matrix represents a document (or a file) from your input. Each column represents a word in the entire vocabulary of all documents. In the cells, you will find the counter for the frequency of a word from the vocabulary in the document.

Now generate the Bag of Words with the CountVectorizer and check:
* the total number of different words
* the total number of words per document
* the total number of occurences of each word

### The total number of different words

I get the total number of different words by using `len(df.columns)` to return the number of columns in the DataFrame. I ignore upper and lower case and consider words such as `the` and `the` as not different.

In [5]:
diffnumWordsTotal = len(df.columns)
print("\nTotal number of different words: ", diffnumWordsTotal)

Total number of different words:  8879

There are a total of 8879 different words, whereby upper and lower case was ignored.  If there is a high number of dimensions, we should try to reduce the number of dimensions. In our case the total number of 8879 different words leads to high number of dimensions.

### The total number of words per document

I get the total number of words per document by calculating the sum of the words for each line of the DataFrame. A document is one row in our data set, so we take the sum of the rows

In [6]:
numWordsPerDoc = df.sum(axis=1)
display("the total number of words per document", numWordsPerDoc)

'the total number of words per document'

0    107416
1      7258
2      7775
3      7497
4      8242
dtype: int64

The output shows the total number of words per document by clearly showing that document 1 `d0` has the most words.

### The total number of occurences of each word

I determine the total number of occurrences of each word by calculating the sum of the occurrences of each column. Each feature dimension is a single word, so I go over the columns.

In [7]:
numOccurencesPerWord = df.sum(axis=0)
display("the total number of occurences of each word", numOccurencesPerWord)

'the total number of occurences of each word'

117        2
12         1
12s        1
13         1
131        2
          ..
zealous    1
zenith     1
zest       1
zigzag     1
zoo        1
Length: 8879, dtype: int64

By reducing the dimension, it is most likely possible to make better statements regarding the occurrence of a word, as there are currently too many stop words or words with low information to make good statements.

## 6.2.2 Which word is occuring the most?

This must be done in three steps. Reason is, that the vectorizer.vocabulary_ is organized as a dictonary with the value indicating the position of the word in the array
1. Find out the highest count of a word
2. Find out the position of this count
3. Find out the word at this position

### Print the Vocabulary to represents the assignment of words to index positions in the vector

In [8]:
vocabulary_ = vectorizer.vocabulary_
display("vocabulary_= ",vocabulary_)

'vocabulary_= '

{'the': 7921,
 'return': 6563,
 'of': 5385,
 'sherlock': 7015,
 'holmes': 3843,
 'collection': 1528,
 'adventures': 190,
 'by': 1142,
 'sir': 7146,
 'arthur': 487,
 'conan': 1614,
 'doyle': 2454,
 'adventure': 189,
 'empty': 2687,
 'house': 3902,
 'it': 4319,
 'was': 8572,
 'in': 4038,
 'spring': 7411,
 'year': 8847,
 '1894': 18,
 'that': 7918,
 'all': 274,
 'london': 4711,
 'interested': 4239,
 'and': 342,
 'fashionable': 2997,
 'world': 8800,
 'dismayed': 2343,
 'murder': 5136,
 'honourable': 3858,
 'ronald': 6649,
 'adair': 150,
 'under': 8269,
 'most': 5101,
 'unusual': 8376,
 'inexplicable': 4115,
 'circumstances': 1411,
 'public': 6126,
 'has': 3701,
 'already': 293,
 'learned': 4565,
 'those': 7967,
 'particulars': 5580,
 'crime': 1898,
 'which': 8659,
 'came': 1171,
 'out': 5460,
 'police': 5852,
 'investigation': 4286,
 'but': 1132,
 'good': 3499,
 'deal': 2055,
 'suppressed': 7725,
 'upon': 8382,
 'occasion': 5365,
 'since': 7138,
 'case': 1241,
 'for': 3207,
 'prosecution': 6097,
 'so': 7264,
 'overwhelmingly': 5502,
 'strong': 7615,
 'not': 5294,
 'necessary': 5207,
 'to': 8053,
 'bring': 1042,
 'forward': 3258,
 'facts': 2946,
 'only': 5411,
 'now': 5317,
 'at': 554,
 'end': 2700,
 'nearly': 5202,
 'ten': 7884,
 'years': 8849,
 'am': 305,
 'allowed': 279,
 'supply': 7718,
 'missing': 5018,
 'links': 4666,
 'make': 4798,
 'up': 8381,
 'whole': 8693,
 'remarkable': 6434,
 'chain': 1289,
 'interest': 4238,
 'itself': 4323,
 'as': 493,
 'nothing': 5304,
 'me': 4898,
 'compared': 1582,
 'inconceivable': 4064,
 'sequel': 6932,
 'afforded': 212,
 'greatest': 3555,
 'shock': 7034,
 'surprise': 7740,
 'any': 386,
 'event': 2808,
 'my': 5164,
 'adventurous': 191,
 'life': 4635,
 'even': 2805,
 'after': 218,
 'this': 7959,
 'long': 4714,
 'interval': 4254,
 'find': 3081,
 'myself': 5166,
 'thrilling': 7989,
 'think': 7948,
 'feeling': 3029,
 'once': 5408,
 'more': 5084,
 'sudden': 7660,
 'flood': 3152,
 'joy': 4380,
 'amazement': 309,
 'incredulity': 4069,
 'utterly': 8414,
 'submerged': 7644,
 'mind': 4987,
 'let': 4608,
 'say': 6783,
 'shown': 7065,
 'some': 7301,
 'glimpses': 3464,
 'have': 3718,
 'occasionally': 5367,
 'given': 3439,
 'them': 7928,
 'thoughts': 7972,
 'actions': 139,
 'very': 8460,
 'man': 4808,
 'they': 7940,
 'are': 446,
 'blame': 864,
 'if': 3970,
 'shared': 6991,
 'knowledge': 4468,
 'with': 8754,
 'should': 7053,
 'considered': 1696,
 'first': 3106,
 'duty': 2551,
 'do': 2398,
 'had': 3630,
 'been': 749,
 'barred': 689,
 'positive': 5889,
 'prohibition': 6067,
 'from': 3320,
 'his': 3821,
 'own': 5507,
 'lips': 4670,
 'withdrawn': 8756,
 'third': 7953,
 'last': 4527,
 'month': 5066,
 'can': 1177,
 'be': 713,
 'imagined': 3989,
 'close': 1469,
 'intimacy': 4258,
 'deeply': 2099,
 'disappearance': 2293,
 'never': 5237,
 'failed': 2951,
 'read': 6290,
 'care': 1211,
 'various': 8435,
 'problems': 6033,
 'before': 756,
 'attempted': 571,
 'than': 7914,
 'private': 6024,
 'satisfaction': 6767,
 'employ': 2679,
 'methods': 4963,
 'their': 7926,
 'solution': 7297,
 'though': 7968,
 'indifferent': 4090,
 'success': 7655,
 'there': 7935,
 'none': 5277,
 'however': 3909,
 'appealed': 405,
 'like': 4644,
 'tragedy': 8110,
 'evidence': 2819,
 'inquest': 4169,
 'led': 4578,
 'verdict': 8455,
 'willful': 8716,
 'against': 222,
 'person': 5708,
 'or': 5435,
 'persons': 5712,
 'unknown': 8330,
 'realized': 6299,
 'clearly': 1447,
 'ever': 2812,
 'done': 2424,
 'loss': 4732,
 'community': 1575,
 'sustained': 7758,
 'death': 2061,
 'were': 8638,
 'points': 5843,
 'about': 70,
 'strange': 7572,
 'business': 1125,
 'would': 8810,
 'sure': 7729,
 'specially': 7355,
 'him': 3810,
 'efforts': 2614,
 'supplemented': 7712,
 'probably': 6031,
 'anticipated': 378,
 'trained': 8116,
 'observation': 5351,
 'alert': 261,
 'criminal': 1901,
 'agent': 228,
 'europe': 2798,
 'day': 2048,
 'drove': 2516,
 'round': 6668,
 'turned': 8215,
 'over': 5478,
 'found': 3261,
 'no': 5264,
 'explanation': 2893,
 'appeared': 411,
 'adequate': 163,
 'risk': 6620,
 'telling': 7874,
 'twice': 8225,
 'told': 8060,
 'tale': 7820,
 'will': 8715,
 'recapitulate': 6318,
 'known': 4469,
 'conclusion': 1634,
 'second': 6868,
 'son': 7310,
 'earl': 2565,
 'maynooth': 4895,
 'time': 8033,
 'governor': 3516,
 'one': 5409,
 'australian': 598,
 'colonies': 1533,
 'mother': 5102,
 'returned': 6564,
 'australia': 597,
 'undergo': 8270,
 'operation': 5422,
 'cataract': 1251,
 'she': 7003,
 'her': 3776,
 'daughter': 2044,
 'hilda': 3805,
 'living': 4688,
 'together': 8057,
 '427': 38,
 'park': 5569,
 'lane': 4510,
 'youth': 8870,
 'moved': 5125,
 'best': 807,
 'society': 7271,
 'far': 2987,
 'enemies': 2712,
 'particular': 5578,
 'vices': 8466,
 'he': 3723,
 'engaged': 2719,
 'miss': 5015,
 'edith': 2598,
 'woodley': 8784,
 'carstairs': 1232,
 'engagement': 2720,
 'broken': 1059,
 'off': 5386,
 'mutual': 5162,
 'consent': 1686,
 'months': 5067,
 'sign': 7108,
 'left': 4583,
 'profound': 6063,
 'behind': 767,
 'rest': 6528,
 'sic': 7089,
 'narrow': 5188,
 'conventional': 1751,
 'circle': 1405,
 'habits': 3628,
 'quiet': 6208,
 'nature': 5194,
 'unemotional': 8289,
 'yet': 8856,
 'easy': 2583,
 'going': 3492,
 'young': 8862,
 'aristocrat': 457,
 'unexpected': 8293,
 'form': 3244,
 'between': 815,
 'hours': 3901,
 'eleven': 2645,
 'twenty': 8224,
 'on': 5407,
 'night': 5252,
 'march': 4836,
 '30': 35,
 'fond': 3191,
 'cards': 1210,
 'playing': 5803,
 'continually': 1735,
 'such': 7659,
 'stakes': 7456,
 'hurt': 3946,
 'member': 4928,
 'baldwin': 660,
 'cavendish': 1269,
 'bagatelle': 648,
 'card': 1207,
 'clubs': 1486,
 'dinner': 2278,
 'played': 5801,
 'rubber': 6677,
 'whist': 8679,
 'latter': 4534,
 'club': 1484,
 'also': 294,
 'afternoon': 219,
 'who': 8691,
 'mr': 5129,
 'murray': 5148,
 'john': 4359,
 'hardy': 3686,
 'colonel': 1531,
 'moran': 5080,
 'showed': 7062,
 'game': 3367,
 'fairly': 2962,
 'equal': 2765,
 'fall': 2966,
 'might': 4974,
 'lost': 4734,
 'five': 3116,
 'pounds': 5915,
 'fortune': 3255,
 'considerable': 1692,
 'could': 1820,
 'way': 8598,
 'affect': 204,
 'every': 2813,
 'other': 5452,
 'cautious': 1267,
 'player': 5802,
 'usually': 8409,
 'rose': 6659,
 'winner': 8735,
 'partnership': 5585,
 'actually': 147,
 'won': 8775,
 'much': 5131,
 'four': 3264,
 'hundred': 3926,
 'sitting': 7150,
 'weeks': 8629,
 'godfrey': 3487,
 'milner': 4984,
 'lord': 4729,
 'balmoral': 663,
 'recent': 6326,
 'history': 3824,
 'evening': 2806,
 'exactly': 2826,
 'sister': 7147,
 'spending': 7372,
 'relation': 6407,
 'servant': 6941,
 'deposed': 2166,
 'heard': 3736,
 'enter': 2746,
 'front': 3321,
 'room': 6652,
 'floor': 3154,
 'generally': 3400,
 'used': 8402,
 'lit': 4677,
 'fire': 3097,
 'smoked': 7241,
 'opened': 5416,
 'window': 8728,
 'sound': 7327,
 'until': 8370,
 'hour': 3899,
 'lady': 4486,
 'desiring': 2192,
 'door': 2428,
 'locked': 4699,
 'inside': 4185,
 'answer': 369,
 'got': 3510,
 'cries': 1897,
 'knocking': 4461,
 'help': 3766,
 'obtained': 5360,
 'forced': 3212,
 'unfortunate': 8301,
 'lying': 4771,
 'near': 5198,
 'table': 7808,
 'head': 3724,
 'horribly': 3886,
 'mutilated': 5159,
 'an': 334,
 'expanding': 2873,
 'revolver': 6582,
 'bullet': 1094,
 'weapon': 8612,
 'sort': 7322,
 'lay': 4551,
 'two': 8234,
 'banknotes': 675,
 'each': 2558,
 'seventeen': 6960,
 'silver': 7124,
 'gold': 3493,
 'money': 5055,
 'arranged': 470,
 'little': 4683,
 'piles': 5751,
 'varying': 8438,
 'amount': 324,
 'figures': 3068,
 'sheet': 7009,
 'paper': 5555,
 'names': 5180,
 'friends': 3306,
 'opposite': 5429,
 'conjectured': 1675,
 'endeavouring': 2703,
 'losses': 4733,
 'winnings': 8737,
 'minute': 4996,
 'examination': 2829,
 'served': 6944,
 'complex': 1598,
 'place': 5776,
 'reason': 6307,
 'why': 8698,
 'fastened': 3001,
 'possibility': 5897,
 'murderer': 5138,
 'afterwards': 220,
 'escaped': 2777,
 'drop': 2512,
 'least': 4571,
 'feet': 3032,
 'bed': 740,
 'crocuses': 1914,
 'full': 3336,
 'bloom': 898,
 'beneath': 792,
 'neither': 5223,
 'flowers': 3164,
 'nor': 5280,
 'earth': 2577,
 'having': 3720,
 'disturbed': 2391,
 'marks': 4848,
 'strip': 7606,
 'grass': 3538,
 'separated': 6930,
 'road': 6626,
 'apparently': 403,
 'therefore': 7936,
 'himself': 3812,
 'how': 3908,
 'did': 2253,
 'come': 1544,
 'climbed': 1462,
 'without': 8762,
 'leaving': 4575,
 'traces': 8101,
 'suppose': 7721,
 'fired': 3098,
 'through': 7995,
 'indeed': 4074,
 'shot': 7051,
 'inflict': 4125,
 'deadly': 2054,
 'wound': 8812,
 'again': 221,
 'is': 4314,
 'frequented': 3297,
 'thoroughfare': 7964,
 'cab': 1145,
 'stand': 7466,
 'within': 8761,
 'yards': 8843,
 'dead': 2053,
 'mushroomed': 5152,
 'soft': 7275,
 'nosed': 5291,
 'bullets': 1095,
 'inflicted': 4126,
 'must': 5156,
 'caused': 1264,
 'instantaneous': 4203,
 'mystery': 5169,
 'further': 3346,
 'complicated': 1600,
 'entire': 2752,
 'absence': 78,
 'motive': 5107,
 'said': 6738,
 'enemy': 2713,
 'attempt': 570,
 'made': 4779,
 'remove': 6452,
 'valuables': 8424,
 'these': 7939,
 'hit': 3825,
 'theory': 7934,
 'reconcile': 6341,
 'line': 4657,
 'resistance': 6512,
 'poor': 5873,
 'friend': 3303,
 'declared': 2084,
 'starting': 7481,
 'point': 5840,
 'confess': 1651,
 'progress': 6066,
 'strolled': 7613,
 'across': 134,
 'six': 7153,
 'clock': 1468,
 'oxford': 5512,
 'street': 7583,
 'group': 3593,
 'loafers': 4691,
 'pavements': 5622,
 'staring': 7475,
 'directed': 2283,
 'see': 6884,
 'tall': 7827,
 'thin': 7945,
 'coloured': 1538,
 'glasses': 3453,
 'whom': 8696,
 'strongly': 7618,
 'suspected': 7751,
 'being': 769,
 'plain': 5782,
 'clothes': 1476,
 'detective': 2222,
 'pointing': 5842,
 'while': 8661,
 'others': 5453,
 'crowded': 1927,
 'listen': 4672,
 'what': 8646,
 'observations': 5352,
 'seemed': 6890,
 'absurd': 85,
 'withdrew': 8757,
 'disgust': 2334,
 'struck': 7619,
 'elderly': 2634,
 'deformed': 2114,
 'knocked': 4459,
 'down': 2450,
 'several': 6962,
 'books': 947,
 'carrying': 1231,
 'remember': 6441,
 'picked': 5736,
 'observed': 5354,
 'title': 8052,
 'origin': 5446,
 'tree': 8149,
 'worship': 8806,
 'fellow': 3035,
 'bibliophile': 820,
 'either': 2623,
 'trade': 8109,
 'hobby': 3828,
 'collector': 1529,
 'obscure': 5348,
 'volumes': 8518,
 'endeavoured': 2702,
 'apologize': 398,
 'accident': 98,
 'evident': 2820,
 'unfortunately': 8302,
 'maltreated': 4807,
 'precious': 5941,
 'objects': 5343,
 'eyes': 2934,
 'owner': 5509,
 'snarl': 7254,
 'contempt': 1730,
 'heel': 3758,
 'saw': 6780,
 'curved': 1983,
 'back': 636,
 'white': 8682,
 'side': 7091,
 'whiskers': 8674,
 'disappear': 2292,
 'among': 322,
 'throng': 7994,
 'clear': 1443,
 'problem': 6032,
 'low': 4748,
 'wall': 8545,
 'railing': 6231,
 'high': 3799,
 'perfectly': 5679,
 'anyone': 388,
 'get': 3420,
 'into': 4263,
 'garden': 3374,
 'entirely': 2753,
 'inaccessible': 4039,
 'waterpipe': 8588,
 'anything': 389,
 'active': 140,
 'climb': 1461,
 'puzzled': 6178,
 'retraced': 6556,
 'steps': 7519,
 'kensington': 4418,
 'study': 7629,
 'minutes': 4998,
 'when': 8652,
 'maid': 4791,
 'entered': 2747,
 'desired': 2190,
 'astonishment': 548,
 'old': 5400,
 'book': 944,
 'sharp': 6994,
 'wizened': 8769,
 'face': 2937,
 'peering': 5649,
 'frame': 3274,
 'hair': 3633,
 'dozen': 2455,
 'wedged': 8625,
 'right': 6604,
 'arm': 459,
 'you': 8861,
 're': 6283,
 'surprised': 7741,
 'croaking': 1911,
 'voice': 8513,
 'acknowledged': 124,
 'well': 8634,
 've': 8440,
 'conscience': 1683,
 'chanced': 1297,
 'go': 3483,
 'hobbling': 3827,
 'thought': 7969,
 'll': 4689,
 'just': 4399,
 'step': 7515,
 'kind': 4440,
 'gentleman': 3408,
 'tell': 7872,
 'bit': 844,
 'gruff': 3605,
 'manner': 4819,
 'harm': 3691,
 'meant': 4905,
 'obliged': 5345,
 'picking': 5737,
 'too': 8067,
 'trifle': 8165,
 'may': 4893,
 'ask': 506,
 'knew': 4451,
 'isn': 4316,
 'great': 3553,
 'liberty': 4622,
 'neighbour': 5219,
 'yours': 8867,
 'bookshop': 948,
 'corner': 1788,
 'church': 1397,
 'happy': 3677,
 'maybe': 4894,
 'collect': 1525,
 'yourself': 8868,
 'here': 3779,
 'british': 1052,
 'birds': 840,
 'catullus': 1260,
 'holy': 3844,
 'war': 8558,
 'bargain': 682,
 'fill': 3072,
 'gap': 3372,
 'shelf': 7011,
 'looks': 4723,
 'untidy': 8369,
 'does': 2409,
 'look': 4719,
 'cabinet': 1148,
 'standing': 7468,
 'smiling': 7237,
 'stared': 7474,
 'seconds': 6869,
 'utter': 8411,
 'then': 7930,
 'appears': 412,
 'fainted': 2956,
 'certainly': 1283,
 'gray': 3549,
 'mist': 5020,
 'swirled': 7788,
 'cleared': 1444,
 'collar': 1523,
 'ends': 2709,
 'undone': 8283,
 'tingling': 8041,
 'taste': 7849,
 'brandy': 998,
 'bending': 791,
 'chair': 1290,
 'flask': 3134,
 'hand': 3648,
 'dear': 2060,
 'watson': 8591,
 'remembered': 6442,
 'owe': 5504,
 'thousand': 7973,
 'apologies': 397,
 'idea': 3960,
 'affected': 205,
 'gripped': 3579,
 'arms': 462,
 'cried': 1896,
 'really': 6301,
 'alive': 273,
 'possible': 5898,
 'succeeded': 7654,
 'climbing': 1463,
 'awful': 625,
 'abyss': 88,
 'wait': 8533,
 'moment': 5050,
 'fit': 3111,
 'discuss': 2323,
 'things': 7947,
 'serious': 6938,
 'unnecessarily': 8340,
 'dramatic': 2468,
 'reappearance': 6303,
 'hardly': 3684,
 'believe': 775,
 'heavens': 3750,
 'men': 4936,
 'sleeve': 7192,
 'felt': 3039,
 'sinewy': 7139,
 'spirit': 7380,
 'anyhow': 387,
 'chap': 1307,
 'overjoyed': 5488,
 'sit': 7149,
 'dreadful': 2481,
 'chasm': 1329,
 'sat': 6766,
 'cigarette': 1400,
 'nonchalant': 5276,
 'dressed': 2491,
 'seedy': 6885,
 'frockcoat': 3319,
 'merchant': 4943,
 'individual': 4098,
 'pile': 5749,
 'looked': 4720,
 'thinner': 7952,
 'keener': 4407,
 'tinge': 8039,
 'aquiline': 437,
 'recently': 6327,
 'healthy': 3733,
 'glad': 3442,
 'stretch': 7591,
 'joke': 4364,
 'take': 7816,
 'foot': 3196,
 'stature': 7497,
 'matter': 4886,
 'explanations': 2894,
 'we': 8602,
 'your': 8866,
 'cooperation': 1773,
 'hard': 3679,
 'dangerous': 2018,
 'work': 8791,
 'us': 8399,
 'perhaps': 5685,
 'better': 813,
 'gave': 3392,
 'account': 109,
 'situation': 7152,
 'finished': 3095,
 'curiosity': 1965,
 'prefer': 5952,
 'hear': 3735,
 'where': 8654,
 'days': 2050,
 'shall': 6979,
 'mouthful': 5123,
 'need': 5212,
 'difficulty': 2264,
 'getting': 3422,
 'simple': 7129,
 'note': 5298,
 'absolutely': 81,
 'genuine': 3413,
 'doubt': 2440,
 'career': 1213,
 'perceived': 5673,
 'somewhat': 7307,
 'sinister': 7144,
 'figure': 3067,
 'late': 4529,
 'professor': 6054,
 'moriarty': 5086,
 'pathway': 5610,
 'safety': 6735,
 'inexorable': 4114,
 'purpose': 6158,
 'exchanged': 2841,
 'remarks': 6438,
 'courteous': 1842,
 'permission': 5693,
 'write': 8830,
 'short': 7046,
 'received': 6323,
 'box': 982,
 'stick': 7526,
 'walked': 8542,
 'along': 289,
 'still': 7529,
 'heels': 3760,
 'reached': 6285,
 'stood': 7544,
 'bay': 711,
 'drew': 2493,
 'rushed': 6712,
 'threw': 7986,
 'around': 466,
 'anxious': 384,
 'revenge': 6571,
 'tottered': 8085,
 'brink': 1045,
 'baritsu': 683,
 'japanese': 4337,
 'system': 7805,
 'wrestling': 8821,
 'useful': 8403,
 'slipped': 7201,
 'grip': 3578,
 'horrible': 3885,
 'scream': 6826,
 'kicked': 4429,
 'madly': 4780,
 'few': 3049,
 'clawed': 1437,
 'air': 251,
 'both': 965,
 'hands': 3659,
 'balance': 656,
 'went': 8637,
 'rock': 6639,
 'bounded': 976,
 'splashed': 7386,
 'water': 8582,
 'listened': 4673,
 'delivered': 2138,
 'puffs': 6137,
 'tracks': 8107,
 'path': 5608,
 'instant': 4202,
 'disappeared': 2294,
 'extraordinarily': 2919,
 'lucky': 4754,
 'chance': 1296,
 'fate': 3006,
 'placed': 5777,
 'sworn': 7793,
 'three': 7984,
 'whose': 8697,
 'desire': 2189,
 'vengeance': 8448,
 'increased': 4066,
 'leader': 4556,
 'convinced': 1761,
 'liberties': 4621,
 'soon': 7313,
 'themselves': 7929,
 'open': 5415,
 'sooner': 7314,
 'later': 4531,
 'destroy': 2209,
 'announce': 361,
 'land': 4501,
 'rapidly': 6262,
 'brain': 992,
 'act': 135,
 'bottom': 970,
 'reichenbach': 6398,
 'examined': 2831,
 'rocky': 6642,
 'picturesque': 5742,
 'assert': 523,
 'sheer': 7008,
 'literally': 4678,
 'true': 8188,
 'small': 7223,
 'footholds': 3199,
 'presented': 5971,
 'indication': 4088,
 'ledge': 4579,
 'cliff': 1460,
 'obvious': 5363,
 'impossibility': 4016,
 'equally': 2766,
 'impossible': 4017,
 'wet': 8643,
 'reversed': 6579,
 'boots': 951,
 'similar': 7127,
 'occasions': 5368,
 'sight': 7104,
 'sets': 6952,
 'direction': 2285,
 'suggested': 7673,
 'deception': 2074,
 'pleasant': 5807,
 'roared': 6630,
 'fanciful': 2981,
 'give': 3438,
 'word': 8788,
 'screaming': 6828,
 'mistake': 5021,
 'fatal': 3005,
 'tufts': 8206,
 'notches': 5297,
 'gone': 3497,
 'struggled': 7621,
 'upward': 8393,
 'deep': 2096,
 'covered': 1852,
 'green': 3558,
 'moss': 5099,
 'lie': 4631,
 'unseen': 8357,
 'perfect': 5678,
 'comfort': 1547,
 'stretched': 7592,
 'following': 3187,
 'investigating': 4285,
 'sympathetic': 7798,
 'inefficient': 4109,
 'formed': 3246,
 'inevitable': 4111,
 'totally': 8083,
 'erroneous': 2773,
 'conclusions': 1635,
 'departed': 2154,
 'hotel': 3896,
 'alone': 288,
 'occurrence': 5377,
 'surprises': 7742,
 'store': 7552,
 'huge': 3914,
 'falling': 2969,
 'above': 71,
 'boomed': 950,
 'past': 5600,
 'looking': 4721,
 'darkening': 2030,
 ...}

### Find out the highest count of a word

The variable `numOccurencesPerWord` is an array which contains the number of occurrences of each word. 

The [max()](https://pandas.pydata.org/docs/reference/api/pandas.Series.max.html) function finds the highest value in the array and stores this value in a new variable `highest_count_of_word`.

In [9]:
highest_count_of_word = numOccurencesPerWord.max(axis=0)
print("\nHighest count of a word:", highest_count_of_word, "\n")

Highest count of a word: 7975

### Find out the word at this position

By using the [idmax()](https://pandas.pydata.org/docs/reference/api/pandas.Series.idxmax.html) function, I return the word with the highest occurrence. 

In this case the row label is the word I am searching for, and the maximum value is the highest count of a word

In [10]:
word_with_highest_occurence = numOccurencesPerWord.idxmax()
print("\nWord with the highest occurence:", word_with_highest_occurence, "\n")

Word with the highest occurence: the

The word with the highest number of occurrences is the word `the` with a number of 7975 counts. I even expected this result, because `the` is one of the stop words that occur too often

### Find out the position of this count

After that, I use the variable in which the word with the highest number is stored as the key for the [vocabulary_](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) function and display the position of the word.

In [11]:
position_of_word = vocabulary_[word_with_highest_occurence]
print("\nPosition of the word:", position_of_word, "\n")

Position of the word: 7921

# 6.3 Improving using stop word, ngrams and tf-idf
The feature space is vast with nearly 9000 dimensions. Hence we should try to reduce the number of dimensions by:

1. use only words that have a mimimum occurence in all documents (minimal document frequency) min_df
2. remove stop words (like 'a', 'and', 'the') as they don't give valuable information for classification and/or 
3. remove words that occur in many documents (maximum document frequency) max_df 

Experiment with the values of min_df and max_df and see how the size of the vocabulary is changing.

Implement all three options and check for their separate outcome an their combinations

To reduce the number of dimensions, I remove all stop words so that the words that contain no information are removed. 

In addition, I tell the CountVectoriser with `min_df=3` and `max_df=0.75` that words that occur in less than 3 documents and words that occur in more than 75% of the documents are ignored.

To get some semantics, I create bigrams `ngram_range=(2,2)`, which are sequences of two consecutive words.

In [12]:
# your code here
improvingVectorizer = CountVectorizer(input="filename", ngram_range=(2,2), stop_words="english",max_df=0.75, min_df=3)
Y = improvingVectorizer.fit_transform(filenames).toarray()
Y

array([[ 1, 12,  5,  6,  1,  1,  1,  5,  1,  1,  1,  1,  6,  1, 12,  2,
         1,  8,  1,  4,  4,  5,  2, 10,  3, 11,  1,  1,  1,  4,  3,  8,
         3,  3, 21,  2,  3,  2,  1,  1,  1,  8,  2,  1,  1,  3,  2,  1,
         1,  2,  1,  2,  4,  3,  1,  3,  2,  3,  1,  6,  4,  4, 10,  3,
         1,  2,  1,  2,  7, 13,  4,  3,  1, 11,  3,  1,  1,  1,  2,  0,
         1,  2,  1,  1,  2,  2,  1, 10,  3,  2, 10,  3,  1,  1,  1,  1,
         2,  2,  4,  2,  1,  1, 25,  1,  1,  1,  2,  8, 43],
       [ 1,  0,  2,  1,  0,  0,  1,  0,  1,  1,  1,  0,  1,  1,  0,  0,
         1,  0,  1,  0,  0,  3,  0,  2,  1,  0,  0,  0,  1,  0,  0,  1,
         0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  2,  0,  1,  2,  0,  0,
         0,  0,  0,  1,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  1,  0,  0,  2,  0,  0,  0,  0,  0,  1,  1,  1,  0,  1,
         0,  0,  1,  2,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,
         1,  0,  2,  0,  0,  1,  0,  0,  1,  1,  1,  1,  2],
       [ 0,  5,  1,  0,  1,  0,  1,  0,  0,  1,  0,  0,  2,  1,  1,  1,
         1,  0,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  2,  1,  0,  1,  1,  1,  2,  0,  1,  1,  0,  0,  1,
         1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  2,  1,
         1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  0,  1,  1,  1,  0,  0,
         1,  0,  0,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  0,  1,
         1,  1,  1,  1,  0,  1,  0,  1,  1,  1,  0,  1,  3],
       [ 1,  0,  0,  0,  0,  1,  0,  1,  1,  0,  0,  1,  0,  0,  1,  0,
         0,  1,  0,  0,  1,  0,  1,  1,  0,  1,  1,  0,  0,  0,  0,  0,
         1,  0,  0,  0,  1,  1,  1,  1,  1,  1,  0,  1,  0,  3,  1,  1,
         0,  1,  0,  0,  1,  0,  1,  0,  0,  0,  1,  0,  1,  0,  1,  0,
         1,  1,  0,  1,  2,  0,  0,  1,  0,  1,  1,  0,  0,  0,  1,  1,
         0,  1,  0,  0,  0,  1,  1,  0,  0,  0,  1,  1,  1,  0,  1,  0,
         0,  1,  0,  0,  1,  0,  1,  0,  0,  0,  1,  0,  0],
       [ 0,  1,  0,  1,  1,  1,  0,  1,  0,  0,  1,  1,  0,  0,  0,  1,
         0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  1,  1,  0,
         0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,
         1,  0,  1,  0,  0,  0,  0,  1,  0,  1,  0,  2,  0,  1,  0,  1,
         0,  0,  0,  0,  0,  0,  6,  0,  1,  0,  1,  0,  0,  0,  1,  1,
         1,  1,  1,  0,  0,  0,  0,  2,  0,  1,  1,  0,  0,  1,  0,  1,
         0,  0,  0,  1,  1,  0,  2,  1,  0,  0,  0,  0,  0]])

In the following, I will use the same pattern to analyse the text as above before I adapted my CountVectorizer to reduce the number of dimensions !

In [13]:
df2 = pd.DataFrame(data=Y, columns=improvingVectorizer.get_feature_names_out())
df2

,able tell,asked holmes,bearded man,blue eyes,came examine,chair stared,closed book,closed door,come evening,come look,...,time ago,took heels,waited bit,watson said,wednesday tuesday,window mr,window way,wish know,yes said,young man
0,1,12,5,6,1,1,1,5,1,1,...,2,1,1,25,1,1,1,2,8,43
1,1,0,2,1,0,0,1,0,1,1,...,0,0,1,0,0,1,1,1,1,2
2,0,5,1,0,1,0,1,0,0,1,...,1,0,1,0,1,1,1,0,1,3
3,1,0,0,0,0,1,0,1,1,0,...,0,1,0,1,0,0,0,1,0,0
4,0,1,0,1,1,1,0,1,0,0,...,1,1,0,2,1,0,0,0,0,0

In [14]:
diffnumWordsTotal2 = len(df2.columns)
numwordsperdoc2 = df2.sum(axis=1)
numOccurencesPerWord2 = df2.sum(axis=0)
display("Total number of different words: ", diffnumWordsTotal2, "the total number of words per document", numwordsperdoc2, "the total number of occurences of each word", numOccurencesPerWord2)

'Total number of different words: '

109

'the total number of words per document'

0    417
1     53
2     98
3     52
4     49
dtype: int64

'the total number of occurences of each word'

able tell        3
asked holmes    18
bearded man      8
blue eyes        8
came examine     3
                ..
window mr        3
window way       3
wish know        4
yes said        10
young man       48
Length: 109, dtype: int64

As you can easily see, I have reduced the number of dimensions from, 9000 to 109. 

In fact, it makes a big difference if I leave stop words in or not. If I leave stop words in and do not change the other parameters, the dimension increases by 1500. 

However, if I only remove the parameter `max_df=0.75`, the number of dimensions increases by 21. In conclusion, it can be said that the stop words make up a large proportion of the words in the documents.

### Print the Vocabulary to represents the assignment of words to index positions in the vector

In [15]:
vocabulary_2 = improvingVectorizer.vocabulary_
display("vocabulary_= ",vocabulary_2)

'vocabulary_= '

{'good deal': 23,
 'sitting room': 90,
 'young man': 108,
 'watson said': 102,
 'holmes cried': 29,
 'moment later': 59,
 'making way': 52,
 'took heels': 100,
 'quite certain': 74,
 'mrs hudson': 62,
 'friend watson': 21,
 'half past': 25,
 'quarter hour': 73,
 'open door': 68,
 'blue eyes': 3,
 'holmes face': 31,
 'like man': 42,
 'holmes said': 34,
 'dressing gown': 17,
 'yes said': 107,
 'sake don': 81,
 'motive crime': 61,
 'ground floor': 24,
 'opened door': 69,
 'asked holmes': 1,
 'oh yes': 67,
 'shook head': 87,
 'far know': 19,
 'did know': 14,
 'little man': 45,
 'said little': 78,
 'know little': 37,
 'holmes examined': 30,
 'think mr': 98,
 'slip paper': 91,
 'tell said': 96,
 'wish know': 106,
 'single word': 88,
 'looked round': 51,
 'public house': 71,
 'dear sir': 12,
 'bearded man': 2,
 'man want': 55,
 'police station': 70,
 'morrow morning': 60,
 'sat deep': 82,
 'chair stared': 5,
 'come evening': 8,
 'holmes rising': 33,
 'hat head': 26,
 'mean say': 57,
 'knows matter': 39,
 'sequence events': 85,
 'key pocket': 35,
 'window mr': 104,
 'head turned': 27,
 'man beard': 53,
 'wednesday tuesday': 103,
 'door saw': 15,
 'little house': 44,
 'know methods': 38,
 'sir good': 89,
 'room contained': 75,
 'let hear': 41,
 'second person': 84,
 'south american': 93,
 'shall come': 86,
 'come look': 9,
 'murdered man': 63,
 'doubt fact': 16,
 'thing said': 97,
 'window way': 105,
 'struck light': 95,
 'long silence': 49,
 'frightened eyes': 22,
 'closed book': 6,
 'fellow said': 20,
 'll said': 47,
 'man words': 56,
 'time ago': 99,
 'line investigation': 43,
 'room ground': 76,
 'night went': 66,
 'night mr': 65,
 'second man': 83,
 'holmes glanced': 32,
 'room took': 77,
 'know did': 36,
 'mister said': 58,
 'hear say': 28,
 'pulled knife': 72,
 'sailor man': 80,
 'man met': 54,
 'look face': 50,
 'waited bit': 101,
 'came examine': 4,
 'did heard': 13,
 'smoked pipe': 92,
 'end time': 18,
 'nearing end': 64,
 'leave country': 40,
 'll send': 48,
 'closed door': 7,
 'staggered feet': 94,
 'little problem': 46,
 'able tell': 0,
 'dear holmes': 11,
 'day day': 10,
 'said putting': 79}

In [16]:
highest_count_of_word2 = numOccurencesPerWord2.max(axis=0)
word_with_highest_occurence2 = numOccurencesPerWord2.idxmax()
position_of_word2 = vocabulary_2[word_with_highest_occurence2]
display("Highest count of a word: " + str(highest_count_of_word2), "Word with the highest occurence: " + str(word_with_highest_occurence2), "Position of the word: " + str(position_of_word2))

'Highest count of a word: 48'

'Word with the highest occurence: young man'

'Position of the word: 108'

After improving the bag of words, the highest count of a word was reduced from, 7975 to 48. 

By removing the stop words and using `min_df` and `max_df` with the `ngrams`, the word "the" no longer occurs, so that the word combination "young man" is the word with the highest occurrence.

This could indicate that it is a central term or a recurring term in the text.

# 6.4 Rescaling the data using term frequency inverse document frequency
Here, term frequency is the number of occurences of a term (word) $t$ in a document $d$. 

$\operatorname{tf}(t, d) = f_{t, d}$ 

Sometimes tf gets normalized to the length of $d$
The inverse document frequency idf is a measure on the amount of information a term t carries. Rare occurences of t leads to a high amount of information common occurence to a low amount of information. The idf is computed as 

$\text{idf}(t) = \log{\frac{1 + n}{1+\text{df}(t)}} + 1$

where $n$ is the total number of documents and $\text{df}(t)$ is the number of documents that contain the term $t$. Hence, the tf-idf is the product of the two terms:

$\text{tf-idf(t,d)}=\text{tf(t,d)} \cdot \text{idf(t)}$

scikit-learn supports this in the `TfidfTransformer`, when using the following parameters: `TfidfTransformer(norm='l2', use_idf=True, smooth_idf=True, sublinear_tf=False)`. Refer to the scikit documentation for the parameter sets and how this changes the formula.

Combining Bag of Words and tf-idf can be done using the `TfidfVectorizer`

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer(input="filename", ngram_range=(2,2),stop_words="english", max_df=0.75, min_df=3)
X_tfidf = pd.DataFrame(tfidf_vect.fit_transform(filenames).toarray(), columns=tfidf_vect.get_feature_names_out())
X_tfidf

,able tell,asked holmes,bearded man,blue eyes,came examine,chair stared,closed book,closed door,come evening,come look,...,time ago,took heels,waited bit,watson said,wednesday tuesday,window mr,window way,wish know,yes said,young man
0,0.014316,0.171797,0.071582,0.085899,0.014316,0.014316,0.014316,0.071582,0.014316,0.014316,...,0.028633,0.014316,0.014316,0.357911,0.014316,0.014316,0.014316,0.028633,0.114531,0.615606
1,0.115470,0.000000,0.230940,0.115470,0.000000,0.000000,0.115470,0.000000,0.115470,0.115470,...,0.000000,0.000000,0.115470,0.000000,0.000000,0.115470,0.115470,0.115470,0.115470,0.230940
2,0.000000,0.428746,0.085749,0.000000,0.085749,0.000000,0.085749,0.000000,0.000000,0.085749,...,0.085749,0.000000,0.085749,0.000000,0.085749,0.085749,0.085749,0.000000,0.085749,0.257248
3,0.129099,0.000000,0.000000,0.000000,0.000000,0.129099,0.000000,0.129099,0.129099,0.000000,...,0.000000,0.129099,0.000000,0.129099,0.000000,0.000000,0.000000,0.129099,0.000000,0.000000
4,0.000000,0.108465,0.000000,0.108465,0.108465,0.108465,0.000000,0.108465,0.000000,0.000000,...,0.108465,0.108465,0.000000,0.216930,0.108465,0.000000,0.000000,0.000000,0.000000,0.000000

Each word now possesses a TF-IDF value when it appears in a document, or zero if it is absent in a document (row of the matrix).

# 6.4.1 Find maximum value for each of the features over dataset

In this section, we will find the maximum value for each feature in the dataset.

We generate a single value for each term, indicating its significance in the classification of a document

To make it a little clearer and more obvious, I have displayed the first 20 and the last 20 features with their maximum values to make the difference in value clearer.

In [18]:
# your code here
max_values = X_tfidf.max(axis=0)
sorted_by_tfidf = max_values.argsort()
feature_names = X_tfidf.columns
print("Features with lowest tfidf:\n{}".format(
    feature_names[sorted_by_tfidf[:20]]))
print("\ntf-idf values:\n{}".format(max_values.iloc[sorted_by_tfidf[:20]]))
print("\nFeatures with highest tfidf: \n{}".format(
    feature_names[sorted_by_tfidf[-20:]]))
print("\ntf-idf values:\n{}".format(max_values.iloc[sorted_by_tfidf[-20:]]))

Features with lowest tfidf:
Index(['came examine', 'door saw', 'holmes examined', 'far know',
       'head turned', 'holmes cried', 'motive crime', 'holmes rising',
       'murdered man', 'look face', 'll send', 'mean say', 'sailor man',
       'struck light', 'south american', 'pulled knife', 'time ago',
       'wednesday tuesday', 'sir good', 'little house'],
      dtype='object')

tf-idf values:
came examine         0.108465
door saw             0.108465
holmes examined      0.108465
far know             0.108465
head turned          0.108465
holmes cried         0.108465
motive crime         0.108465
holmes rising        0.108465
murdered man         0.108465
look face            0.108465
ll send              0.108465
mean say             0.108465
sailor man           0.108465
struck light         0.108465
south american       0.108465
pulled knife         0.108465
time ago             0.108465
wednesday tuesday    0.108465
sir good             0.108465
little house         0.115470
dtype: float64

Features with highest tfidf:
Index(['let hear', 'dear sir', 'mrs hudson', 'did know', 'shook head',
       'moment later', 'like man', 'think mr', 'bearded man', 'second man',
       'opened door', 'good deal', 'open door', 'holmes said', 'friend watson',
       'watson said', 'little man', 'asked holmes', 'young man',
       'police station'],
      dtype='object')

tf-idf values:
let hear          0.171499
dear sir          0.171499
mrs hudson        0.171499
did know          0.171797
shook head        0.216930
moment later      0.216930
like man          0.230940
think mr          0.230940
bearded man       0.230940
second man        0.230940
opened door       0.230940
good deal         0.230940
open door         0.258199
holmes said       0.300645
friend watson     0.346410
watson said       0.357911
little man        0.387298
asked holmes      0.428746
young man         0.615606
police station    0.650791
dtype: float64

##### Features with lowest tf-idf:

The words listed have low TF-IDF values, which indicates that they occur frequently in the documents analysed and have a low information across all documents. They could be everyday words or stop words that are less important for understanding the text. In our case, stop words were removed so that represent typical phrases in the entire text corpus or are not very relevant with regard to classify a document.

##### Features mit höchstem tf-idf:

Words with high TF-IDF values are less common throughout the corpus, and are words that indicate high information.

##### General conclusions:

Words like "holmes examined" and "mean say" exhibit low TF-IDF values, suggesting that they are common phrases across the entire text corpus. The phrase "night went" stands out with a slightly higher TF-IDF value among the lower values, implying that this word pairing occurs less frequently and may offer more nuanced context. Terms, such as "mrs hudson" and "watson," show higher TF-IDF values, signifying their heightened presence in specific sections of the texts.